name: Garden
main: me.simplex.garden.Garden
version: 0.0.1
website: http://over9000.eu
author: simplex
startup: startup
description: VORONOI, VORONOI EVERYWHERE
commands:
  garden:
    aliases: [g,grdn]
    description: Generates a new Garden-World and ports you into it
    usage: /<command> [worldname] [seed]
permissions:
  garden.*:
    description: Gives access to the /garden command
    children:
      garden.command: true