name: Garden
main: me.simplex.garden.Garden
version: 0.0.1
website: http://over9000.eu
author: simplex
startup: startup
description: WGEN lolwut
commands:
  garden:
    aliases: [g,grdn]
    description: Generates a new Garden-World and ports you into it
    usage: /<command>